### ISSUE TITLE
Reconnect does not work when captcha is enabled

### ISSUE THREAD

**Issue by am11** [kiwiirc/kiwiirc#1211] opened 2020-01-02 19:37 UTC
For some reason, I have not managed to use "reconnect" functionality when using https://webchat.freenode.net/ in FireFox (using the latest version 71.0). The <kbd>Reconnect to #channel-name</kbd> button appears, clicking on it shows `Connecting` followed by a spinner indefinitely. At that point the error message `Invalid captcha` shows up in server messages:

![image](https://user-images.githubusercontent.com/3840695/71688037-ccfad380-2da7-11ea-8afa-90fa94836d6a.png)

**Comment by ItsOnlyBinary** [comment] 2020-01-02 20:36
Duplicate of #1200

**Closed by ItsOnlyBinary** 2020-01-02 20:36 UTC
