### ISSUE TITLE
backticks are not evaluated when followed by non-whitespace

### ISSUE THREAD

**Issue by stdedos** [kiwiirc/kiwiirc#1378] opened 2020-07-01 21:39 UTC
![image](https://user-images.githubusercontent.com/133706/86293896-309d7680-bbfc-11ea-9eac-6c3bf5ef5e8d.png)

> stdedos: Hello everyone, and good month! Is there a way for `git fetch` to default to `--all`? In the Github Fork/PR model, I have the `master->origin/master`, which means I would have to at least `git fetch upstream` to absorb remote changes

... would you just opt for switching to https://github.com/commonmark/commonmark-spec instead? 😕 

May make everyone's life more tranquil

**Comment by ItsOnlyBinary** [comment] 2021-06-04 08:42
duplicate of #1433

closing this older one so i don't miss my comment in the newer one. please don't create any more for this issue

**Closed by ItsOnlyBinary** 2021-06-04 08:42 UTC
