### ISSUE TITLE
Error with yarn build

### ISSUE THREAD

**Issue by djlolito** [kiwiirc/kiwiirc#656] opened 2018-11-07 12:36 UTC
Version: webpack 3.12.0
Time: 45564ms
                                                  Asset       Size  Chunks                    Chunk Names
                 static/img/kiwiLoadingLogo.ee10be5.png    19.6 kB          [emitted]
             static/img/fontawesome-webfont.912ec66.svg     444 kB          [emitted]  [big]
           static/fonts/fontawesome-webfont.b06871f.ttf     166 kB          [emitted]
           static/fonts/fontawesome-webfont.674f50d.eot     166 kB          [emitted]
          static/fonts/fontawesome-webfont.fee66e7.woff      98 kB          [emitted]
         static/fonts/fontawesome-webfont.af7ae50.woff2    77.2 kB          [emitted]
               static/js/vendor.b5c55d402252fcb06140.js     626 kB       0  [emitted]  [big]  vendor
                  static/js/app.d9571ee0474b9fbc88e7.js     363 kB       1  [emitted]  [big]  app
             static/js/manifest.37a2ecbb1d1b7e6c9ada.js  856 bytes       2  [emitted]         manifest
    static/css/app.670e584feb80828b587f4f17c0c4201c.css    68.7 kB       1  [emitted]         app
static/css/app.670e584feb80828b587f4f17c0c4201c.css.map     129 kB          [emitted]
           static/js/vendor.b5c55d402252fcb06140.js.map    4.39 MB       0  [emitted]         vendor
              static/js/app.d9571ee0474b9fbc88e7.js.map       2 MB       1  [emitted]         app
         static/js/manifest.37a2ecbb1d1b7e6c9ada.js.map    9.24 kB       2  [emitted]         manifest
                                             index.html  814 bytes          [emitted]
                              static/locales/en-us.json    9.76 kB          [emitted]
                                     static/config.json  989 bytes          [emitted]
                             static/emoticons/smile.png    4.42 kB          [emitted]
                                     static/favicon.png    4.29 kB          [emitted]
                                   static/highlight.mp3    3.82 kB          [emitted]
                              static/locales/af-za.json    6.56 kB          [emitted]
                              static/locales/cs-cz.json    5.41 kB          [emitted]
                              static/locales/da-dk.json    5.41 kB          [emitted]
                              static/locales/es-em.json    6.53 kB          [emitted]
                              static/locales/fi-fi.json    5.41 kB          [emitted]
                              static/locales/hu-hu.json    5.59 kB          [emitted]
                              static/locales/ja-jp.json    5.41 kB          [emitted]
                              static/locales/ko-kr.json    5.41 kB          [emitted]
                              static/locales/no-no.json    5.41 kB          [emitted]
                              static/locales/ro-ro.json    5.41 kB          [emitted]
                              static/locales/ru-ru.json    5.48 kB          [emitted]
                              static/locales/sl-si.json    5.41 kB          [emitted]
                              static/locales/sq-al.json    7.44 kB          [emitted]
                              static/locales/sr-sp.json    5.41 kB          [emitted]
                              static/locales/sv-se.json    5.41 kB          [emitted]
                              static/locales/tr-tr.json    5.61 kB          [emitted]
                              static/locales/vi-vn.json    5.41 kB          [emitted]
                              static/locales/zh-tw.json    5.41 kB          [emitted]
                              static/locales/ar-sa.json     9.3 kB          [emitted]
                              static/locales/bg-bg.json    13.8 kB          [emitted]
                              static/locales/bs-ba.json    10.1 kB          [emitted]
                              static/locales/ca-es.json    10.3 kB          [emitted]
                              static/locales/de-de.json      10 kB          [emitted]
                                static/locales/dev.json    9.74 kB          [emitted]
                              static/locales/el-gr.json    14.7 kB          [emitted]
                              static/locales/es-ar.json    10.2 kB          [emitted]
                              static/locales/es-es.json    10.3 kB          [emitted]
                              static/locales/es-us.json    10.2 kB          [emitted]
                              static/locales/eu-es.json    9.21 kB          [emitted]
                              static/locales/fr-fr.json    8.72 kB          [emitted]
                              static/locales/gl-es.json    10.2 kB          [emitted]
                              static/locales/he-il.json     9.1 kB          [emitted]
                              static/locales/id-id.json     8.5 kB          [emitted]
                              static/locales/it-it.json    10.6 kB          [emitted]
                              static/locales/nl-nl.json    10.3 kB          [emitted]
                              static/locales/pl-pl.json    9.93 kB          [emitted]
                              static/locales/pt-br.json    10.3 kB          [emitted]
                              static/locales/pt-pt.json    10.4 kB          [emitted]
                              static/locales/uk-ua.json    13.5 kB          [emitted]
                              static/locales/zh-cn.json    8.96 kB          [emitted]
                         static/themes/coffee/theme.css    24.3 kB          [emitted]
                        static/themes/default/theme.css    23.4 kB          [emitted]
                        static/themes/grayfox/theme.css    23.8 kB          [emitted]
                         static/themes/osprey/theme.css      24 kB          [emitted]
                            static/themes/sky/theme.css    23.7 kB          [emitted]
                           static/themes/dark/theme.css    25.4 kB          [emitted]
                    static/themes/nightswatch/theme.css    26.8 kB          [emitted]
                    static/themes/radioactive/theme.css    25.4 kB          [emitted]

ERROR in
src/components/NetworkSettings.vue
 291:5  ✖  Expected indentation of 0 spaces   indentation
 292:5  ✖  Expected indentation of 0 spaces   indentation
 293:5  ✖  Expected indentation of 0 spaces   indentation
 294:5  ✖  Expected indentation of 0 spaces   indentation

  Build failed with errors.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ItsOnlyBinary** [comment] 2018-11-07 12:41
Could you please provide, OS version, node version and yarn version

**Comment by djlolito** [comment] 2018-11-07 12:44
> Could you please provide, OS version, node version and yarn version

Centos 6 , node v11.1.0 , yarn 1.12.1

Thx

**Comment by ItsOnlyBinary** [comment] 2018-11-07 12:47
i suspect you did `npm install` if im correct delete your node_modules folder and use `yarn install`
yarn install does specific version of modules, and i think that error is caused by a newer linter module

**Comment by djlolito** [comment] 2018-11-07 12:56
> oes specific version of modules, and i think t

Yes thx !!!!

**Comment by ItsOnlyBinary** [comment] 2018-11-07 13:00
excellent, I will close this issue now :) if you have any future problems drop your questions in an issue, or feel free to join us in #kiwiirc on irc.freenode.net
https://kiwiirc.com/nextclient/irc.freenode.net

**Closed by ItsOnlyBinary** 2018-11-07 13:00 UTC
