### ISSUE TITLE
Major sidebar mess on mobile

### ISSUE THREAD

**Issue by CoryChaplin** [kiwiirc/kiwiirc#1343] opened 2020-05-31 20:19 UTC
On the mobile, the sidebars get totally messed up when switching channels making Kiwi near impossible to use.
Here's a sample taken from https://builds.kiwiirc.com/kiwiirc/master/ with Chrome in a 470x706 window.

![mobile-sidebar-mess](https://user-images.githubusercontent.com/5139669/83361839-9d6aea00-a38c-11ea-8bbe-5d42914cc2d9.gif)

**Comment by bogdomania** [comment] 2020-05-31 20:28
yeah, if u tap on the people icon, it will act normal, no biggie.

**Comment by bogdomania** [comment] 2020-06-01 14:16
Is this a duplicate of #1314 ?

**Comment by CoryChaplin** [comment] 2020-06-01 21:55
Definitely

**Comment by xam60** [comment] 2020-06-05 10:06
Putting a setTimeout on the setActiveBuffer function of StateBrowserNetwork seems to be a working workaround 
`setActiveBuffer: function switchContainer(buffer) {
// Clear any active component to show the buffer again
this.$state.$emit('active.component', null);
if (this.$state.ui.is_narrow) {
this.$state.$emit('statebrowser.hide');
setTimeout(() => {
this.$state.setActiveBuffer(buffer.networkid, buffer.name);
}, 200);
} else {
this.$state.setActiveBuffer(buffer.networkid, buffer.name);
}
},`

**Comment by CoryChaplin** [comment] 2020-06-08 21:48
This regression was introduced during refactoring of state, shortly after this https://github.com/kiwiirc/kiwiirc/commit/1473d1b4f4bfe7363c353145e75d4d0f6f4628ee

**Comment by ItsOnlyBinary** [comment] 2020-06-09 23:23
Its caused by this commit https://github.com/kiwiirc/kiwiirc/commit/a7bb8e1f3b0ad40b0117c7432e6635f71e3d4765

**Comment by westor7** [comment] 2020-06-21 17:31
A short reproduce video: https://bit.ly/2AZpb26

**Comment by prawnsalad** [comment] 2020-09-21 12:21
Fixed in master :)

**Closed** 2020-09-21 12:21 UTC
