### ISSUE TITLE
Backticks are not closed if there is no space

### ISSUE THREAD

**Issue by stdedos** [kiwiirc/kiwiirc#1286] opened 2020-04-22 12:22 UTC
> [...] (A: `git log --pretty=oneline`) [...]

is typed as:

> [...] (A: `git log --pretty=oneline``) [...]

(minus the 3rd backtick, I don't remember how to escape them in cleartext)

**Comment by ItsOnlyBinary** [comment] 2021-06-04 08:41
duplicate of #1433

closing this older one so i don't miss my comment in the newer one. please don't create any more for this issue

**Closed by ItsOnlyBinary** 2021-06-04 08:41 UTC
