### ISSUE TITLE
Broken user count

### ISSUE THREAD

**Issue by CoryChaplin** [kiwiirc/kiwiirc#165] opened 2018-01-01 22:58 UTC
After a few hours on a large traffic channel (above 600 users with massive join/parts), the counter is at 1000 users instead of 660.

**Comment by prawnsalad** [comment] 2018-05-26 23:58
Is this still an issue? I can't say I've seen this happen as yet after using the new version full time for several months.

**Comment by CoryChaplin** [comment] 2018-06-03 14:16
I'll check again.

**Comment by ItsOnlyBinary** [comment] 2018-06-28 18:16
I have left my home server connected to some big channels for several days an have not managed to reproduce this issue. All counts are still correct

**Comment by AllanOcelot** [comment] 2019-02-19 12:06
Has not been raised again as an issue since 2018 - so closing this issue.

**Closed by AllanOcelot** 2019-02-19 12:06 UTC
