### ISSUE TITLE
Webirc bug

### ISSUE THREAD

**Issue by Shadowgr** [kiwiirc/kiwiirc#109] opened 2017-09-20 20:06 UTC
Hello there, in my network setup already the new version of kiwiirc and works ok with webirc enabled.

I see one connection from proxy and webirc auth not works, but other users connected with real ips. The logs from server:

*** Looking up your hostname.. 21:46:48

my.server*** Checking Ident 21:46:48

my.server*** Got Ident response 21:46:48

my.server*** Found your hostname 21:46:48

, WEBIRC, Not enough parameters

The bug is: , WEBIRC, Not enough parameters

Probably in line 5, kiwi says: cgi:irc set host to ip my hostname

How can be resolve this?

**Comment by prawnsalad** [comment] 2017-09-20 20:11
* Is it just one user with the problem?
* Which network is this so I can try it?
* Can you paste your config somewhere

**Comment by Shadowgr** [comment] 2017-09-21 11:07
Yes the problem is for one user only. Other users connected without any problem.

You can try with this client: http://zeus.chatters.gr:7778

I paste you the user problem:

mirmigi was webchat@web.chatters.gr * Chatters Webchat User

web.chatters.gr isn't a real ip. 

You can see the conf files:

1) http://paste.debian.net/987090/

2) http://paste.debian.net/987092/

**Comment by prawnsalad** [comment] 2017-09-22 13:17
As mentioned on IRC, setting the kiwi servers `logLevel` option to 1 and pasting a log for the users connection will be helpful here.

**Comment by Shadowgr** [comment] 2017-09-22 20:22
Logs:

2017/09/22 23:17:53 L_DEBUG client:34 ws->: NICK mirmigi
2017/09/22 23:17:53 L_DEBUG client:34 ws->: USER mirmigi 0 * https://kiwiirc.com/
2017/09/22 23:17:53 L_INFO client:34 Using pre-set upstream
2017/09/22 23:17:53 L_DEBUG client:34 ->upstream: WEBIRC getpass321 websocketgateway  46.166.142.222

2017/09/22 23:17:53 L_DEBUG client:34 signal:state connected
2017/09/22 23:17:53 L_DEBUG client:34 ->upstream: CAP LS 302
2017/09/22 23:17:53 L_DEBUG client:34 upstream->: :web.chatters.gr NOTICE AUTH :*** Looking up your hostname...
2017/09/22 23:17:53 L_DEBUG client:34 upstream->: :web.chatters.gr NOTICE AUTH :*** Checking Ident
2017/09/22 23:17:53 L_DEBUG client:34 signal:data :web.chatters.gr NOTICE AUTH :*** Looking up your hostname...
2017/09/22 23:17:53 L_DEBUG client:34 signal:data :web.chatters.gr NOTICE AUTH :*** Checking Ident
2017/09/22 23:17:53 L_DEBUG client:34 upstream->: :web.chatters.gr NOTICE AUTH :*** No Ident response
2017/09/22 23:17:53 L_DEBUG client:34 signal:data :web.chatters.gr NOTICE AUTH :*** No Ident response
2017/09/22 23:17:53 L_DEBUG client:34 upstream->: :web.chatters.gr NOTICE AUTH :*** Found your hostname
2017/09/22 23:17:53 L_DEBUG client:34 upstream->: :web.chatters.gr 461  WEBIRC :Not enough parameters
2017/09/22 23:17:53 L_DEBUG client:34 signal:data :web.chatters.gr NOTICE AUTH :*** Found your hostname
2017/09/22 23:17:53 L_DEBUG client:34 signal:data :web.chatters.gr 461  WEBIRC :Not enough parameters
2017/09/22 23:17:54 L_DEBUG client:34 ->upstream: NICK mirmigi
2017/09/22 23:17:54 L_DEBUG client:34 ->upstream: USER 2ea68ede 0 * :Chatters Webchat User

**Comment by Shadowgr** [comment] 2017-09-22 20:23
check the line: 2017/09/22 23:17:53 L_DEBUG client:34 upstream->: :web.chatters.gr 461 WEBIRC :Not enough parameters

This is a bug? ://

**Comment by prawnsalad** [comment] 2017-09-22 20:27
Thanks for that. I see the issue is with the client DNS resolving now - I'll try get this resolved this weekend.

**Comment by prawnsalad** [comment] 2017-10-14 20:50
Oops, forgot to update this issue some time ago. But this issue has been fixed in the latest webircgateway project.

**Closed by prawnsalad** 2017-10-14 20:50 UTC
