### ISSUE TITLE
webirc password ?

### ISSUE THREAD

**Issue by ircalem** [kiwiirc/kiwiirc#252] opened 2018-03-16 07:55 UTC
(CGI:IRC -- No access ) problem

where do we write the password ?

config.json
------------------------------------
{
"windowTitle": "Kiwi IRC - The web IRC client",
"startupScreen": "welcome",
"kiwiServer": "https://localdev.clients.kiwiirc.com/webirc/kiwiirc/",
"restricted": true,
"theme": "default",
"themes": [
{ "name": "Default", "url": "static/themes/default" }
],
"startupOptions" : {
"server": "irc.ircalem.com",
"port": 6667,
"tls": false,
"direct": true,
"channel": "#sohbet",
"nick": "kiwi-n?"
},
"embedly": {
"key": ""
}
}

**Comment by TheMythPT** [comment] 2018-03-16 08:04
You need to edit `/etc/kiwiirc/config.conf` (on Debian/Ubuntu) and set the password there. just read the configuration carefully.

**Comment by ircalem** [comment] 2018-03-16 08:20
show a sample config.conf file.

**Comment by prawnsalad** [comment] 2018-03-16 12:17
Duplicate of https://github.com/kiwiirc/kiwiirc/issues/251

**Closed by prawnsalad** 2018-03-16 12:17 UTC
