### ISSUE TITLE
Participant list not changing when switching channels

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwiirc#1265] opened 2020-04-02 08:24 UTC
This is a new issue as of today. In the console I see these which are possibly related (talking about SidebarState after all):

```
TypeError: "e.buffer is null"
    i App.vue:7
    VueJS 7
vue.common.prod.js:6:11571

TypeError: "this.$state.getActiveBuffer(...) is null"
    section SidebarState.vue:49
    section Sidebar.vue:63
    VueJS 3
    i Sidebar.vue:1
    VueJS 7
vue.common.prod.js:6:11571
```

So the effect is that the participant list of a particular channel is frozen in place even while I switch to any other channel.

**Comment by ItsOnlyBinary** [comment] 2020-04-04 17:17
Are you able to explain the steps to reproduce this?

**Comment by mestaritonttu** [comment] 2020-04-04 17:24
I haven't been able to repro this again.

**Comment by prawnsalad** [comment] 2020-05-09 14:50
Closing as we can't reproduce this. Please re-open this is you do find it happening again

**Closed by prawnsalad** 2020-05-09 14:50 UTC
