### ISSUE TITLE
Toggle extra text buttons doesn't reopen

### ISSUE THREAD

**Issue by cristiancs** [kiwiirc/kiwiirc#600] opened 2018-10-07 23:01 UTC
If you start typing and then hit the toggle, you can't reopen the menu.

![toggle](http://g.recordit.co/MsKG3X6JWU.gif)

**Comment by ItsOnlyBinary** [comment] 2018-10-07 23:06
Thanks for your bug reports :)
this one is a duplicate of #583 so im going to close it

**Closed by ItsOnlyBinary** 2018-10-07 23:06 UTC
