### ISSUE TITLE
Capture Button on Upload Image from Camera

### ISSUE THREAD

**Issue by TurtleChatRooms** [kiwiirc/kiwiirc#863] opened 2019-03-11 20:14 UTC
![capture button](https://user-images.githubusercontent.com/43826343/54154609-2e793c80-443a-11e9-94df-29e2f50433a1.jpg)

Cant see the capture button on Samsung S8 Plus

**Comment by prawnsalad** [comment] 2019-03-13 10:55
Closing as a duplicate of https://github.com/kiwiirc/plugin-fileuploader/issues/54

**Closed by prawnsalad** 2019-03-13 10:55 UTC
