### ISSUE TITLE
Emply result in channel list tab 

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#250] opened 2018-03-14 13:57 UTC
Channel list tab don't show channels, both using list command or refresh button.  
Enabling raw notices you can see ircd answer in server tab.

**Comment by AllanOcelot** [comment] 2018-06-01 14:08
On the latest master build, channel list is displaying as intended, so I'm marking this as closed :)

**Closed by AllanOcelot** 2018-06-01 14:08 UTC
